/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.OrdemDeServicoDao;
import DOMAIN.OrdemDeServico;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class OrdemDeServicoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form OrdemDeServicoVIEW
     */
    public OrdemDeServicoVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOServ = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordem de Serviço");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Incluir Serviço");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAlterar.setText("Alterar Serviço");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btExcluir.setText("Excluir Serviço");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pesquisar Ordem de Serviço pelo Nome do Cliente:");

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        tbOServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbOServ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbOServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbOServMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbOServ);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButton1)
                .addGap(63, 63, 63)
                .addComponent(btAlterar)
                .addGap(64, 64, 64)
                .addComponent(btExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton2)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(307, 307, 307))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir))
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(924, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        IncluirOrdemDeServicoVIEW tela = new IncluirOrdemDeServicoVIEW();
        tela.setVisible(true);
        tela.setResizable(false);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
    
        try {
            OrdemDeServicoDao cDao = new OrdemDeServicoDao();
            OrdemDeServico ods = new OrdemDeServico();
            int linhaSelecionada=tbOServ.getSelectedRow();
            ods.setId(Integer.parseInt(tbOServ.getModel().getValueAt(linhaSelecionada, 0).toString()));
            System.out.println(ods.getId());
            ResultSet rs = cDao.selecionarOrdem(ods);
            
            
            while (rs.next()){
                int id = rs.getInt(1);               
                String dataE = rs.getString(3);
                String situacao = rs.getString(5);
                
                AlterarOrdemDeServicoVIEW tela = new AlterarOrdemDeServicoVIEW();
                tela.setVisible(true);
                tela.setResizable(false);
                tela.recebeCliente(id, dataE, situacao);
                tela.setVisible(true);
                tela.setResizable(false);
            }} catch (SQLException ex) {
            System.out.println(ex.getMessage());;
        }
        btExcluir.setEnabled(false);
        btAlterar.setEnabled(false);
         
    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
        btAlterar.setEnabled(false);  
        btExcluir.setEnabled(false);
        OrdemDeServicoDao odsDao = new OrdemDeServicoDao();
        ResultSet rs = odsDao.pesquisarODSPorNome(txtPesquisa.getText());
        carregarDadosNaJTable(rs);
        
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        OrdemDeServicoDao oDao = new OrdemDeServicoDao();
        ResultSet rs = oDao.pegarDadosParaTabela();
        carregarDadosNaJTable(rs);
     
    }//GEN-LAST:event_formWindowOpened

    private void tbOServMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOServMousePressed
        
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        
    }//GEN-LAST:event_tbOServMousePressed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
        
        OrdemDeServicoDao odsDao= new OrdemDeServicoDao();
        OrdemDeServico ods = new OrdemDeServico();
        int linhaSelecionada = tbOServ.getSelectedRow();
        int codigo = Integer.parseInt(tbOServ.getModel().getValueAt(linhaSelecionada, 0).toString());
        
        ods.setId(codigo);
        odsDao.excluirODS(ods);
        
        btExcluir.setEnabled(false);
        btAlterar.setEnabled(false);
        ResultSet rs= odsDao.pegarDadosParaTabela();
        carregarDadosNaJTable(rs);
        
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        txtPesquisa.setText("");
        OrdemDeServicoDao odsDao= new OrdemDeServicoDao();
        ResultSet rs= odsDao.pegarDadosParaTabela();
        carregarDadosNaJTable(rs);
        
    }//GEN-LAST:event_jButton2ActionPerformed
       
    public void carregarDadosNaJTable(ResultSet rs){
        
        try{
            String colunas []= {"id", "Cliente", "Data de Entrega", "Situação", "Valor Total" };
            DefaultTableModel modelo = new DefaultTableModel(null,colunas);
            tbOServ.setModel (modelo);
            
            while (rs.next()){
                String linha[]= {rs.getString("idOrdemDeServico"), rs.getString("nome"), rs.getString("dtEntrega"), rs.getString("situacao"), rs.getString("valorTotal")};
                modelo.addRow(linha);    
            }
        }catch(Exception e){
            System.out.println("Erro ao Carregar JTable");
            System.out.println(e.getMessage());
        }
    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServicoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServicoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServicoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServicoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemDeServicoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOServ;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
